package classsys;

public class OpcodesUtil {

    public static String[] opcodeVerbose;
    public static final int NOP = 0x00;        //0
    public static final int ACONST_NULL = 0x01;//1
    public static final int ICONST_M1 = 0x02;  //2
    public static final int ICONST_0 = 0x03;   //3
    public static final int ICONST_1 = 0x04;   //4
    public static final int ICONST_2 = 0x05;   //5
    public static final int ICONST_3 = 0x06;   //6
    public static final int ICONST_4 = 0x07;   //7
    public static final int ICONST_5 = 0x08;   //8
    public static final int LCONST_0 = 0x09;   //9
    public static final int LCONST_1 = 0x0a;//10
    public static final int FCONST_0 = 0x0b;
    public static final int FCONST_1 = 0x0c;
    public static final int FCONST_2 = 0x0d;
    public static final int DCONST_0 = 0x0e;
    public static final int DCONST_1 = 0x0f;//15
    public static final int BIPUSH = 0x10;
    public static final int SIPUSH = 0x11;
    public static final int LDC = 0x12;
    public static final int LDC_W = 0x13;
    public static final int LDC2_W = 0x14;//20
    public static final int ILOAD = 0x15;
    public static final int LLOAD = 0x16;
    public static final int FLOAD = 0x17;
    public static final int DLOAD = 0x18;
    public static final int ALOAD = 0x19;//25
    public static final int ILOAD_0 = 0x1a;
    public static final int ILOAD_1 = 0x1b;
    public static final int ILOAD_2 = 0x1c;
    public static final int ILOAD_3 = 0x1d;
    public static final int LLOAD_0 = 0x1e;//30
    public static final int LLOAD_1 = 0x1f;
    public static final int LLOAD_2 = 0x20;
    public static final int LLOAD_3 = 0x21;
    public static final int FLOAD_0 = 0x22;
    public static final int FLOAD_1 = 0x23;//35
    public static final int FLOAD_2 = 0x24;
    public static final int FLOAD_3 = 0x25;
    public static final int DLOAD_0 = 0x26;
    public static final int DLOAD_1 = 0x27;
    public static final int DLOAD_2 = 0x28;//40
    public static final int DLOAD_3 = 0x29;
    public static final int ALOAD_0 = 0x2a;
    public static final int ALOAD_1 = 0x2b;
    public static final int ALOAD_2 = 0x2c;
    public static final int ALOAD_3 = 0x2d;//45
    public static final int IALOAD = 0x2e;
    public static final int LALOAD = 0x2f;
    public static final int FALOAD = 0x30;
    public static final int DALOAD = 0x31;
    public static final int AALOAD = 0x32;//50
    public static final int BALOAD = 0x33;
    public static final int CALOAD = 0x34;
    public static final int SALOAD = 0x35;
    public static final int ISTORE = 0x36;
    public static final int LSTORE = 0x37;//55
    public static final int FSTORE = 0x38;
    public static final int DSTORE = 0x39;
    public static final int ASTORE = 0x3a;
    public static final int ISTORE_0 = 0x3b;
    public static final int ISTORE_1 = 0x3c;//60
    public static final int ISTORE_2 = 0x3d;
    public static final int ISTORE_3 = 0x3e;
    public static final int LSTORE_0 = 0x3f;
    public static final int LSTORE_1 = 0x40;
    public static final int LSTORE_2 = 0x41;//65
    public static final int LSTORE_3 = 0x42;
    public static final int FSTORE_0 = 0x43;
    public static final int FSTORE_1 = 0x44;
    public static final int FSTORE_2 = 0x45;
    public static final int FSTORE_3 = 0x46;//70
    public static final int DSTORE_0 = 0x47;
    public static final int DSTORE_1 = 0x48;
    public static final int DSTORE_2 = 0x49;
    public static final int DSTORE_3 = 0x4a;
    public static final int ASTORE_0 = 0x4b;//75
    public static final int ASTORE_1 = 0x4c;
    public static final int ASTORE_2 = 0x4d;
    public static final int ASTORE_3 = 0x4e;
    public static final int IASTORE = 0x4f;
    public static final int LASTORE = 0x50;//80
    public static final int FASTORE = 0x51;//81
    public static final int DASTORE = 0x52;//82
    public static final int AASTORE = 0x53;//83
    public static final int BASTORE = 0x54;//84
    public static final int CASTORE = 0x55;//85
    public static final int SASTORE = 0x56;//86
    public static final int POP = 0x57;    //87
    public static final int POP2 = 0x58;   //88
    public static final int DUP = 0x59;    //89
    public static final int DUP_X1 = 0x5a; //90
    public static final int DUP_X2 = 0x5b;
    public static final int DUP2 = 0x5c;
    public static final int DUP2_X1 = 0x5d;
    public static final int DUP2_X2 = 0x5e;
    public static final int SWAP = 0x5f;//95
    public static final int IADD = 0x60;
    public static final int LADD = 0x61;
    public static final int FADD = 0x62;
    public static final int DADD = 0x63;
    public static final int ISUB = 0x64;//100
    public static final int LSUB = 0x65;
    public static final int FSUB = 0x66;
    public static final int DSUB = 0x67;
    public static final int IMUL = 0x68;
    public static final int LMUL = 0x69;//105
    public static final int FMUL = 0x6a;
    public static final int DMUL = 0x6b;
    public static final int IDIV = 0x6c;
    public static final int LDIV = 0x6d;
    public static final int FDIV = 0x6e;//110
    public static final int DDIV = 0x6f;
    public static final int IREM = 0x70;
    public static final int LREM = 0x71;
    public static final int FREM = 0x72;
    public static final int DREM = 0x73;//115
    public static final int INEG = 0x74;
    public static final int LNEG = 0x75;
    public static final int FNEG = 0x76;
    public static final int DNEG = 0x77;
    public static final int ISHL = 0x78;//120
    public static final int LSHL = 0x79;
    public static final int ISHR = 0x7a;
    public static final int LSHR = 0x7b;
    public static final int IUSHR = 0x7c;
    public static final int LUSHR = 0x7d;//125
    public static final int IAND = 0x7e;
    public static final int LAND = 0x7f;
    public static final int IOR = 0x80;
    public static final int LOR = 0x81;
    public static final int IXOR = 0x82;//130
    public static final int LXOR = 0x83;
    public static final int IINC = 0x84;
    public static final int I2L = 0x85;
    public static final int I2F = 0x86;
    public static final int I2D = 0x87;//135
    public static final int L2I = 0x88;
    public static final int L2F = 0x89;
    public static final int L2D = 0x8a;
    public static final int F2I = 0x8b;
    public static final int F2L = 0x8c;//140
    public static final int F2D = 0x8d;
    public static final int D2I = 0x8e;
    public static final int D2L = 0x8f;
    public static final int D2F = 0x90;
    public static final int I2B = 0x91;//145
    public static final int I2C = 0x92;
    public static final int I2S = 0x93;
    public static final int LCMP = 0x94;
    public static final int FCMPL = 0x95;
    public static final int FCMPG = 0x96;//150
    public static final int DCMPL = 0x97;
    public static final int DCMPG = 0x98;
    public static final int IFEQ = 0x99;
    public static final int IFNE = 0x9a;
    public static final int IFLT = 0x9b;//155
    public static final int IFGE = 0x9c;
    public static final int IFGT = 0x9d;
    public static final int IFLE = 0x9e;
    public static final int IF_ICMPEQ = 0x9f;
    public static final int IF_ICMPNE = 0xa0;//160
    public static final int IF_ICMPLT = 0xa1;
    public static final int IF_ICMPGE = 0xa2;
    public static final int IF_ICMPGT = 0xa3;
    public static final int IF_ICMPLE = 0xa4;
    public static final int IF_ACMPEQ = 0xa5;//165
    public static final int IF_ACMPNE = 0xa6;
    public static final int GOTO = 0xa7;
    public static final int JSR = 0xa8;
    public static final int RET = 0xa9;
    public static final int TABLESWITCH = 0xaa;//170
    public static final int LOOKUPSWITCH = 0xab;
    public static final int IRETURN = 0xac;
    public static final int LRETURN = 0xad;
    public static final int FRETURN = 0xae;
    public static final int DRETURN = 0xaf;//175
    public static final int ARETURN = 0xb0;
    public static final int RETURN = 0xb1;
    public static final int GETSTATIC = 0xb2;
    public static final int PUTSTATIC = 0xb3;
    public static final int GETFIELD = 0xb4;//180
    public static final int PUTFIELD = 0xb5;
    public static final int INVOKEVIRTUAL = 0xb6;
    public static final int INVOKESPECIAL = 0xb7;
    public static final int INVOKESTATIC = 0xb8;
    public static final int INVOKEINTERFACE = 0xb9;//185
    public static final int XXXUNUSEDXXX = 0xba;//186
    public static final int NEW = 0xbb;//187
    public static final int NEWARRAY = 0xbc;//188
    public static final int ANEWARRAY = 0xbd;//189
    public static final int ARRAYLENGTH = 0xbe;//190
    public static final int ATHROW = 0xbf;
    public static final int CHECKCAST = 0xc0;
    public static final int INSTANCEOF = 0xc1;
    public static final int MONITORENTER = 0xc2;
    public static final int MONITOREXIT = 0xc3;//195
    public static final int WIDE = 0xc4;
    public static final int MULTIANEWARRAY = 0xc5;
    public static final int IFNULL = 0xc6;
    public static final int IFNONNULL = 0xc7;
    public static final int GOTO_W = 0xc8;//200
    public static final int JSR_W = 0xc9;
    public static final int BREAKPOINT = 0xca;
    public static final int IMPDEP1 = 0xfe;
    public static final int IMPDEP2 = 0xff;
    public static final int NEWARRAY_T_BOOLEAN = 4;
    public static final int NEWARRAY_T_CHAR = 5;
    public static final int NEWARRAY_T_FLOAT = 6;
    public static final int NEWARRAY_T_DOUBLE = 7;
    public static final int NEWARRAY_T_BYTE = 8;
    public static final int NEWARRAY_T_SHORT = 9;
    public static final int NEWARRAY_T_INT = 10;
    public static final int NEWARRAY_T_LONG = 11;

    static {
        opcodeVerbose = new String[256];
        opcodeVerbose[NOP] = "00 nop";
        opcodeVerbose[ACONST_NULL] = "01 aconst_null";
        opcodeVerbose[ICONST_M1] = "02 iconst_m1";
        opcodeVerbose[ICONST_0] = "03 iconst_0";
        opcodeVerbose[ICONST_1] = "04 iconst_1";
        opcodeVerbose[ICONST_2] = "05 iconst_2";
        opcodeVerbose[ICONST_3] = "06 iconst_3";
        opcodeVerbose[ICONST_4] = "07 iconst_4";
        opcodeVerbose[ICONST_5] = "08 iconst_5";
        opcodeVerbose[LCONST_0] = "03 lconst_0";
        opcodeVerbose[LCONST_1] = "04 lconst_1";
        opcodeVerbose[FCONST_0] = "05 fconst_0";
        opcodeVerbose[FCONST_1] = "06 fconst_1";
        opcodeVerbose[FCONST_2] = "07 fconst_2";
        opcodeVerbose[DCONST_0] = "08 dconst_0";
        opcodeVerbose[DCONST_1] = "09 dconst_1";
        opcodeVerbose[BIPUSH] = "10 bipush";
        opcodeVerbose[SIPUSH] = "11 sipush";
        opcodeVerbose[LDC] = "12 ldc";
        opcodeVerbose[LDC_W] = "13 ldc_w";
        opcodeVerbose[LDC2_W] = "14 ldc2_w";
        opcodeVerbose[ILOAD] = "15 iload";
        opcodeVerbose[LLOAD] = "16 lload";
        opcodeVerbose[FLOAD] = "17 fload";
        opcodeVerbose[DLOAD] = "18 dload";
        opcodeVerbose[ALOAD] = "19 aload";
        opcodeVerbose[ILOAD_0] = "1a iload_0";
        opcodeVerbose[ILOAD_1] = "1b iload_1";
        opcodeVerbose[ILOAD_2] = "1c iload_2";
        opcodeVerbose[ILOAD_3] = "1d iload_3";
        opcodeVerbose[LLOAD_0] = "1e lload_0";
        opcodeVerbose[LLOAD_1] = "1f lload_1";
        opcodeVerbose[LLOAD_2] = "20 lload_2";
        opcodeVerbose[LLOAD_3] = "21 lload_3";
        opcodeVerbose[FLOAD_0] = "22 fload_0";
        opcodeVerbose[FLOAD_1] = "23 fload_1";
        opcodeVerbose[FLOAD_2] = "24 fload_2";
        opcodeVerbose[FLOAD_3] = "25 fload_3";
        opcodeVerbose[DLOAD_0] = "26 dload_0";
        opcodeVerbose[DLOAD_1] = "27 dload_1";
        opcodeVerbose[DLOAD_2] = "28 dload_2";
        opcodeVerbose[DLOAD_3] = "29 dload_3";
        opcodeVerbose[ALOAD_0] = "2a aload_0";
        opcodeVerbose[ALOAD_1] = "2b aload_1";
        opcodeVerbose[ALOAD_2] = "2c aload_2";
        opcodeVerbose[ALOAD_3] = "2d aload_3";
        opcodeVerbose[IALOAD] = "2e iaload";
        opcodeVerbose[LALOAD] = "2f laload";
        opcodeVerbose[FALOAD] = "30 faload";
        opcodeVerbose[DALOAD] = "31 daload";
        opcodeVerbose[AALOAD] = "32 aaload";
        opcodeVerbose[BALOAD] = "33 baload";
        opcodeVerbose[CALOAD] = "34 caload";
        opcodeVerbose[SALOAD] = "35 saload";
        opcodeVerbose[ISTORE] = "36 istore";
        opcodeVerbose[LSTORE] = "37 lstore";
        opcodeVerbose[FSTORE] = "38 fstore";
        opcodeVerbose[DSTORE] = "39 dstore";
        opcodeVerbose[ASTORE] = "3a astore";
        opcodeVerbose[ISTORE_0] = "3b istore_0";
        opcodeVerbose[ISTORE_1] = "3c istore_1";
        opcodeVerbose[ISTORE_2] = "3d istore_2";
        opcodeVerbose[ISTORE_3] = "3e istore_3";
        opcodeVerbose[LSTORE_0] = "3f lstore_0";
        opcodeVerbose[LSTORE_1] = "40 lstore_1";
        opcodeVerbose[LSTORE_2] = "41 lstore_2";
        opcodeVerbose[LSTORE_3] = "42 lstore_3";
        opcodeVerbose[FSTORE_0] = "43 fstore_0";
        opcodeVerbose[FSTORE_1] = "44 fstore_1";
        opcodeVerbose[FSTORE_2] = "45 fstore_2";
        opcodeVerbose[FSTORE_3] = "46 fstore_3";
        opcodeVerbose[DSTORE_0] = "47 dstore_0";
        opcodeVerbose[DSTORE_1] = "48 dstore_1";
        opcodeVerbose[DSTORE_2] = "49 dstore_2";
        opcodeVerbose[DSTORE_3] = "4a dstore_3";
        opcodeVerbose[ASTORE_0] = "4b astore_0";
        opcodeVerbose[ASTORE_1] = "4c astore_1";
        opcodeVerbose[ASTORE_2] = "4d astore_2";
        opcodeVerbose[ASTORE_3] = "4e astore_3";
        opcodeVerbose[IASTORE] = "4f iastore";
        opcodeVerbose[LASTORE] = "50 lastore";
        opcodeVerbose[FASTORE] = "51 fastore";
        opcodeVerbose[DASTORE] = "52 dastore";
        opcodeVerbose[AASTORE] = "53 aastore";
        opcodeVerbose[BASTORE] = "54 bastore";
        opcodeVerbose[CASTORE] = "55 castore";
        opcodeVerbose[SASTORE] = "56 sastore";
        opcodeVerbose[POP] = "57 pop";
        opcodeVerbose[POP2] = "58 pop2";
        opcodeVerbose[DUP] = "59 dup";
        opcodeVerbose[DUP_X1] = "5a dup_x1";
        opcodeVerbose[DUP_X2] = "5b dup_x2";
        opcodeVerbose[DUP2] = "5c dup2";
        opcodeVerbose[DUP2_X1] = "5d dup2_x1";
        opcodeVerbose[DUP2_X2] = "5e dup2_x2";
        opcodeVerbose[SWAP] = "5f swap";
        opcodeVerbose[IADD] = "60 iadd";
        opcodeVerbose[LADD] = "61 ladd";
        opcodeVerbose[FADD] = "62 fadd";
        opcodeVerbose[DADD] = "63 dadd";
        opcodeVerbose[ISUB] = "64 isub";
        opcodeVerbose[LSUB] = "65 lsub";
        opcodeVerbose[FSUB] = "66 fsub";
        opcodeVerbose[DSUB] = "67 dsub";
        opcodeVerbose[IMUL] = "68 imul";
        opcodeVerbose[LMUL] = "69 lmul";
        opcodeVerbose[FMUL] = "6a fmul";
        opcodeVerbose[DMUL] = "6b dmul";
        opcodeVerbose[IDIV] = "6c idiv";
        opcodeVerbose[LDIV] = "6d ldiv";
        opcodeVerbose[FDIV] = "6e fdiv";
        opcodeVerbose[DDIV] = "6f ddiv";
        opcodeVerbose[IREM] = "70 irem";
        opcodeVerbose[LREM] = "71 lrem";
        opcodeVerbose[FREM] = "72 frem";
        opcodeVerbose[DREM] = "73 drem";
        opcodeVerbose[INEG] = "74 ineg";
        opcodeVerbose[LNEG] = "75 lneg";
        opcodeVerbose[FNEG] = "76 fneg";
        opcodeVerbose[DNEG] = "77 dneg";
        opcodeVerbose[ISHL] = "78 ishl";
        opcodeVerbose[LSHL] = "79 lshl";
        opcodeVerbose[ISHR] = "7a ishr";
        opcodeVerbose[LSHR] = "7b lshr";
        opcodeVerbose[IUSHR] = "7c iushr";
        opcodeVerbose[LUSHR] = "7d lushr";
        opcodeVerbose[IAND] = "7e iand";
        opcodeVerbose[LAND] = "7f land";
        opcodeVerbose[IOR] = "80 ior";
        opcodeVerbose[LOR] = "81 lor";
        opcodeVerbose[IXOR] = "82 ixor";
        opcodeVerbose[LXOR] = "83 lxor";
        opcodeVerbose[IINC] = "84 iinc";
        opcodeVerbose[I2L] = "85 i2l";
        opcodeVerbose[I2F] = "86 i2f";
        opcodeVerbose[I2D] = "87 i2d";
        opcodeVerbose[L2I] = "88 l2i";
        opcodeVerbose[L2F] = "89 l2f";
        opcodeVerbose[L2D] = "8a l2d";
        opcodeVerbose[F2I] = "8b f2i";
        opcodeVerbose[F2L] = "8c f2l";
        opcodeVerbose[F2D] = "8d f2d";
        opcodeVerbose[D2I] = "8e d2i";
        opcodeVerbose[D2L] = "8f d2l";
        opcodeVerbose[D2F] = "90 d2f";
        opcodeVerbose[I2B] = "91 i2b";
        opcodeVerbose[I2C] = "92 i2c";
        opcodeVerbose[I2S] = "93 i2s";
        opcodeVerbose[LCMP] = "94 lcmp";
        opcodeVerbose[FCMPL] = "95 fcmpl";
        opcodeVerbose[FCMPG] = "96 fcmpg";
        opcodeVerbose[DCMPL] = "97 dcmpl";
        opcodeVerbose[DCMPG] = "98 dcmpg";
        opcodeVerbose[IFEQ] = "99 ifeq";
        opcodeVerbose[IFNE] = "9a ifne";
        opcodeVerbose[IFLT] = "9b iflt";
        opcodeVerbose[IFGE] = "9c ifge";
        opcodeVerbose[IFGT] = "9d ifgt";
        opcodeVerbose[IFLE] = "9e ifle";
        opcodeVerbose[IF_ICMPEQ] = "9f if_icmpeq";
        opcodeVerbose[IF_ICMPNE] = "a0 if_icmpne";
        opcodeVerbose[IF_ICMPLT] = "a1 if_icmplt";
        opcodeVerbose[IF_ICMPGE] = "a2 if_icmpge";
        opcodeVerbose[IF_ICMPGT] = "a3 if_icmpgt";
        opcodeVerbose[IF_ICMPLE] = "a4 if_icmple";
        opcodeVerbose[IF_ACMPEQ] = "a5 if_acmpeq";
        opcodeVerbose[IF_ACMPNE] = "a6 if_acmpne";
        opcodeVerbose[GOTO] = "a7 goto";
        opcodeVerbose[JSR] = "a8 jsr";
        opcodeVerbose[RET] = "a9 ret";
        opcodeVerbose[TABLESWITCH] = "aa tableswitch";
        opcodeVerbose[LOOKUPSWITCH] = "ab lookupswitch";
        opcodeVerbose[IRETURN] = "ac ireturn";
        opcodeVerbose[LRETURN] = "ad lreturn";
        opcodeVerbose[FRETURN] = "ae freturn";
        opcodeVerbose[DRETURN] = "af dreturn";
        opcodeVerbose[ARETURN] = "b0 areturn";
        opcodeVerbose[RETURN] = "b1 return";
        opcodeVerbose[GETSTATIC] = "b2 getstatic";
        opcodeVerbose[PUTSTATIC] = "b3 putstatic";
        opcodeVerbose[GETFIELD] = "b4 getfield";
        opcodeVerbose[PUTFIELD] = "b5 putfield";
        opcodeVerbose[INVOKEVIRTUAL] = "b6 invokevirtual";
        opcodeVerbose[INVOKESPECIAL] = "b7 invokespecial";
        opcodeVerbose[INVOKESTATIC] = "b8 invokestatic";
        opcodeVerbose[INVOKEINTERFACE] = "b9 invokeinterface";
        opcodeVerbose[XXXUNUSEDXXX] = "ba xxxunusedxxx";
        opcodeVerbose[NEW] = "bb new";
        opcodeVerbose[NEWARRAY] = "bc newarray";
        opcodeVerbose[ANEWARRAY] = "bd anewarray";
        opcodeVerbose[ARRAYLENGTH] = "be arraylength";
        opcodeVerbose[ATHROW] = "bf athrow";
        opcodeVerbose[CHECKCAST] = "c0 checkcast";
        opcodeVerbose[INSTANCEOF] = "c1 instanceof";
        opcodeVerbose[MONITORENTER] = "c2 monitorenter";
        opcodeVerbose[MONITOREXIT] = "c3 monitorexit";
        opcodeVerbose[WIDE] = "c4 wide";
        opcodeVerbose[MULTIANEWARRAY] = "c5 multianewarray";
        opcodeVerbose[IFNULL] = "c6 ifnull";
        opcodeVerbose[IFNONNULL] = "c7 ifnonnull";
        opcodeVerbose[GOTO_W] = "c8 goto_w";
        opcodeVerbose[JSR_W] = "c9 jsr_w";
        opcodeVerbose[BREAKPOINT] = "ca breakpoint";
        opcodeVerbose[IMPDEP1] = "fe impdep1";
        opcodeVerbose[IMPDEP2] = "ff impdep2";

    }

    public static String getVerbose(int opcode) {
        if (opcode < 0 || opcode > 255) {
            return "invalid code";
        } else {
            return opcodeVerbose[opcode];
        }
    }

    public static String getArrayTypeVerbose(int arrayType) {

        switch (arrayType) {
            case NEWARRAY_T_BOOLEAN:
                return "boolean";
            case NEWARRAY_T_CHAR:
                return "char";
            case NEWARRAY_T_FLOAT:
                return "float";
            case NEWARRAY_T_DOUBLE:
                return "double";
            case NEWARRAY_T_BYTE:
                return "byte";
            case NEWARRAY_T_SHORT:
                return "short";
            case NEWARRAY_T_INT:
                return "int";
            case NEWARRAY_T_LONG:
                return "long";
            default:
                return "invalid array type";
        }
    }
}
